root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  bin = "./bin/headless-go-htmx"
  cmd = "npm run build && templ generate && go build -o ./bin/headless-go-htmx ./cmd/main.go"
  delay = 1000
  exclude_dir = ["node_modules", "assets", "tmp", "vendor", "frontend"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "templ", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false
  main_only = false

[misc]
  clean_on_exit = false
  
[screen]
  clear_on_rebuild = false
  keep_scroll = true
